#!/usr/bin/env python3
"""The manuscript's result tables, generated from the recorded results so that no table is copied by
hand (seventh-round review). Writes the table bodies to paper/tables/*.tex, which paper/main.tex
inputs, and the full design comparison (supplementary Table S1) to results/design_table.md.

    python3 scripts/paper_tables.py [--results results] [--out paper/tables]"""
import argparse
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT = "fine_key_plus_fast_resolution (default)"
CARRIERS = ["concentrated_pumper_no_verify", "concentrated_pumper_verifies_instantly",
            "concentrated_pumper_verifies_humanlike", "concentrated_pumper_solves_challenges"]
ATTACKERS = [("naive_single_client", "Single client"), ("datacenter_rotation", "Datacenter rotation"),
             ("premium_pumping", "Premium pumping"), ("sequential_numbers", "Sequential numbers"),
             ("residential_reused_profile", "Reused profile"), ("residential_bot", "Residential bot"),
             ("residential_captcha_farm", "Farmed CAPTCHA"), ("residential_aged_fps", "Aged fingerprints"),
             ("spoofed_platform", "Forged header")]
DESIGNS = [("v1", "v1"), ("v1_corrected", "v1-corrected"), ("budget_only", "budget-only"), ("block_limit_only", "block-limit"),
           ("conversion_only", "conversion-only"), ("speed_only", "speed-only"), ("v2", "v2")]


def n(x, d=0):
    """A number in the manuscript's style: thin space as thousands separator, minus sign in math."""
    if x is None:
        return "--"
    s = f"{abs(x):,.{d}f}".replace(",", "\\,")
    return ("$-$" if x < 0 and round(abs(x), d) != 0 else "") + s


def ci(v, d=0):
    return f"{n(v[0], d)} [{n(v[1], d)}, {n(v[2], d)}]"


def ci2(v, d=0):
    """A mean with its interval on a second, smaller line, so that wide tables stay legible (Table 7 of revision 8)."""
    return f"\\begin{{tabular}}[t]{{@{{}}r@{{}}}}{n(v[0], d)}\\\\{{\\scriptsize [{n(v[1], d)}, {n(v[2], d)}]}}\\end{{tabular}}"


def headline(E):
    ms = E["multi_seed"]
    rows = []
    for key, label in ATTACKERS:
        lifted, on = ms["behavioural_only"][key], ms["with_adaptive_caps"][key]["v2"]
        rows.append(f"{label} & {n(lifted['v1']['leak_fraction_pct'][0], 1)} & {n(lifted['block_limit_only']['leak_fraction_pct'][0], 1)} & "
                    f"{n(lifted['v2']['leak_fraction_pct'][0], 1)} & {n(on['leak_fraction_pct'][0], 1)} & "
                    f"{n(on['first_time_refusal_rate_pct'][0], 1)} & {n(on['legit_completed_pct'][0], 1)} \\\\")
    return "\n".join(rows)


def designs_tex(E):
    """Rows of the in-study benchmark table (Discussion): every design against every source-side
    attacker with source caps lifted, leaked share of attack requests (%, means); intervals in
    results/design_table.md."""
    ms = E["multi_seed"]["behavioural_only"]
    return "\n".join(f"{label} & " + " & ".join(n(ms[key][d]["leak_fraction_pct"][0], 1) for d, _ in DESIGNS) + " \\\\"
                     for key, label in ATTACKERS)


def design_table(E):
    ms = E["multi_seed"]
    L = ["# Supplementary Table S1: every design against every attacker", "",
         "Leaked share of attack requests (%, mean of per-run shares over thirty seeds with 95 % percentile-bootstrap intervals, 20-minute attacks; the data of revision 6's Figure 1), with source caps lifted "
         "(behavioural layers only) and on; and, with caps on, first-time users refused and all legitimate users completing (%). "
         "Generated by `scripts/paper_tables.py` from `results/evaluation.json` (`multi_seed`).", ""]
    for cond, title in (("behavioural_only", "Caps lifted: leaked %"), ("with_adaptive_caps", "Caps on: leaked %"),
                        ("with_adaptive_caps|first_time_refusal_rate_pct", "Caps on: first-time users refused %"),
                        ("with_adaptive_caps|legit_completed_pct", "Caps on: all users completing %")):
        c, _, metric = cond.partition("|")
        metric = metric or "leak_fraction_pct"
        L += [f"## {title}", "", "| Attacker | " + " | ".join(lab for _, lab in DESIGNS) + " |", "|---|" + "---:|" * len(DESIGNS)]
        for key, label in ATTACKERS:
            L.append(f"| {label} | " + " | ".join(f"{ms[c][key][d][metric][0]:.1f} [{ms[c][key][d][metric][1]:.1f}, {ms[c][key][d][metric][2]:.1f}]"
                                                  for d, _ in DESIGNS) + " |")
        L.append("")
    return "\n".join(L) + "\n"


def pumping(E):
    P, LA = E["pumping"], E["long_attack"]
    hl = "concentrated_pumper_verifies_humanlike"

    def row(label, x, codes=True):
        nc = x["n_contained"]
        cont = ci(x["time_to_containment_if_contained_min"], 1) if nc else "--"
        fv = x["first_verdict_min"]
        return (f"{label} & {ci(x['leaked_total'])} & {nc}/{x['n']} & {cont} & {n(fv[0], 1) if fv[0] is not None else '--'} & "
                f"{n(x['attacker_verifications'][0]) if codes else '--'} \\\\")
    rows = [row("never verifies: v1", P[CARRIERS[0]]["v1"]),
            row("\\quad v2 default", P[CARRIERS[0]][DEFAULT]),
            row("verifies within 1\\,s: v2 default", P[CARRIERS[1]][DEFAULT]),
            row("verifies 60\\% after 30\\,s: v2 default", P[hl][DEFAULT]),
            row("\\quad v2 default, 60 min", LA[hl], codes=False),
            row("buys challenges: v2 default", P[CARRIERS[3]][DEFAULT])]
    return "\n".join(rows)


def matched(E):
    M = E["matched"]
    sel = M["selection"]["200"]["chosen"]
    roles = [("none", "none"), ("default", "sequential T1000 c1"),
             ("best sequential at the service target", None), ("best counter_graded_short at the service target", None),
             ("best counter_graded_daily at the service target", None)]
    labels = {"none": "none", "default": "sequential $T1000$, $c1$ (default)"}
    rows = []
    for role, fixed in roles:
        s = fixed or sel[role]
        if role.startswith("best sequential"):
            lab = f"{tex_setting(s)} (selected at tuning target)"
        elif role.startswith("best counter_graded_short"):
            lab = f"{tex_setting(s)} (selected)"
        elif role.startswith("best counter_graded_daily"):
            lab = f"{tex_setting(s)} (selected daily)"
        else:
            lab = labels[role]
        lg = M["legit"]["200"][s]["0.65"]
        benign = "--" if s == "none" else n(M["paired"]["200"][s]["0.65"]["attributable_loss_vs_none"]["net_lost_pct"][0], 2)
        ev = lg["block_verdicts"][0] if isinstance(lg["block_verdicts"], list) else lg["block_verdicts"]
        rows.append(f"{lab} & " + " & ".join(n(M["attack"][s][a]["leaked_total"][0]) for a in CARRIERS) +
                    f" & {n(lg['legit_completed_pct'][0], 2)}\\% & {benign} & {n(lg['legit_challenge_rate_pct'][0], 2)}\\% & {n(ev, 1) if ev else '0'} \\\\")
    return "\n".join(rows)


def tex_setting(s):
    if s.startswith("sequential"):
        _, t, c = s.split()
        return f"sequential ${t}$, ${c}$"
    if s.startswith("counter graded") and "/" in s:
        q, per = s.split()[2].split("/")
        return f"counter, graded, {q} per {per.replace('min', '').strip()} min" if "min" in s else f"counter, graded, {q} per day"
    return s


def claims(CS):
    C = CS["E2"]["claims"]
    stmt = {"K1": "Leaks at most 10\\% of attack requests", "K2": "Attack-free attributable loss at most 0.5 points",
            "K3": "Attributable loss under attack at most 0.5 points", "K4": "Leaks no more than the default sequential tests",
            "K5": "Attributable loss under attack at most the default's plus 0.25 points"}
    rows = []
    for k in ("K1", "K2", "K3", "K4", "K5"):
        c = C[k]
        iv = [f for f in c.get("failing", []) if "instantly" in str(f)]
        iv_cells = None if k == "K2" else 36
        iv_true = "--" if iv_cells is None else f"{iv_cells - len(iv)}/{iv_cells}"
        res = "holds" if c["holds"] else "fails"
        if k == "K4" and c["holds"] and iv_cells and (iv_cells - len(iv)) / iv_cells < 0.9:
            res = "holds pooled, not for IV"
        rows.append(f"{k} & {stmt[k]} & {c['true']}/{c['cells']} ({100 * c['share']:.0f}\\%) & {iv_true} & {res} \\\\")
    return "\n".join(rows)


def attacked(R5):
    A = R5["C_attacked_service"]["200 shared"]
    four = A["four carriers"]
    pols = [("none", "none"), ("sequential T1000 c1", "sequential, default"), ("sequential T300 c0", "sequential $T300$, $c0$"),
            ("counter graded 4/10 min", "counter, 4 per 10 min"), ("counter 4/10 min + sequential", "counter + sequential"),
            ("token bucket 4/10 min burst 4", "token bucket, burst 4"), ("token bucket 4/10 min burst 12", "token bucket, burst 12")]
    ra = []
    for key, lab in pols:
        q = four[key]
        ex, dg, bn = q["vs_attacked_none"], q["vs_attack_free_same_policy"], q["benign_cost"]
        if key == "none":
            ra.append(f"{lab} & {ci2(q['leaked_sum'])} & -- & -- & {n(dg['all']['net_pct'][0], 2)} & {ci2(dg['attacked_block']['net_pct'], 1)} & -- \\\\[1pt]")
        else:
            ra.append(f"{lab} & {ci2(q['leaked_sum'])} & {n(ex['all']['net_pct'][0], 2)} & {ci2(ex['attacked_block']['net_pct'], 1)} & "
                      f"{n(dg['all']['net_pct'][0], 2)} & {ci2(dg['attacked_block']['net_pct'], 1)} & {n(bn['all']['net_pct'][0], 2)} \\\\[1pt]")
    P = A["poisoner"]
    rb = []
    for key, lab in pols:
        if key == "none":
            rb.append(f"{lab} & {n(P[key]['leaked'][0])} & -- & -- \\\\")
            continue
        ex = P[key]["vs_attacked_none"]
        rb.append(f"{lab} & {n(P[key]['leaked'][0])} & {ci(ex['all']['net_pct'], 2)} & {n(ex['first_time']['net_pct'][0], 2)} \\\\")
    users = four["counter graded 4/10 min"]["vs_attacked_none"]["attacked_block"]["users_per_run"][0]
    return "\n".join(ra), "\n".join(rb), users


def figure1_key(E, runs_path):
    """Supplementary key to the matched-comparison figure (Figure 4 of revision 8; Figure 1 until the
    related-work, threat-model and design figures were added; eighth-round review): every setting plotted, with its completion,
    its leakage summed over the four concentrated pumpers' runs of each evaluation seed (95 % percentile-
    bootstrap interval over seeds, as plotted) and the roles the selection gave it."""
    import gzip
    import sys
    sys.path.insert(0, str(ROOT / "src"))
    from otp_guard.evaluation.stats import boot_ci
    M, d = E["matched"], "200"
    sel = M["selection"][d]
    roles = {}
    for role, setting in sel["chosen"].items():
        roles.setdefault(setting, []).append(role)
    acc = {}
    with gzip.open(runs_path, "rt") as f:
        for line in f:
            r = json.loads(line)
            if r.get("study") != "matched_eval" or r["index"][0] != "attack":
                continue
            _, _, setting, _att, seed = r["index"]
            acc.setdefault(setting, {}).setdefault(seed, []).append(r["attack"]["leaked_total"])
    labelled = {v for k, v in sel["chosen"].items() if not k.startswith("matched false")} | {"none", "sequential T1000 c1"}
    L = ["# Key to Figure 4, the matched comparison (supplementary; the file keeps its earlier name)", "",
         "Matched comparison, first protocol, 200 blocks, evaluation seeds 0-9. Completion: 24-hour attack-free runs at 65 % "
         "conversion (mean [95 % CI]). Leaked: 20-minute leakage summed over the four concentrated pumpers' runs of a seed "
         "(mean over seeds [95 % percentile-bootstrap CI]). Roles: what the selection rule chose the setting as on the tuning "
         f"seeds (tuning target {sel['service_target_completion_pct']:.2f} %). Generated by `scripts/paper_tables.py`.", "",
         "In 2.8.x the role 'matched false alarms, credit inf' was held by `sequential T1000 cinf`; in 2.9.0 it is held by "
         "`sequential T300 cinf` (`results/store_change_report.md`). Neither is labelled in Figure 4, and no claim uses the role.", "",
         "| Setting | Labelled in Figure 4 | Completion, % | Leaked, four pumpers summed | Roles |", "|---|---|---|---|---|"]
    rows = []
    for name in M["evaluate"][d]:
        c = M["legit"][d][name]["0.65"]["legit_completed_pct"]
        sums = [sum(v) for v in acc.get(name, {}).values() if len(v) == 4]
        b = boot_ci(sums) if sums else None
        rows.append((b[0] if b else 0, name, c, b))
    for _, name, c, b in sorted(rows, key=lambda x: (x[0], x[1])):
        leak = f"{b[0]:.1f} [{b[1]:.1f}, {b[2]:.1f}]" if b else "--"
        L.append(f"| {name} | {'yes' if name in labelled else 'no'} | {c[0]:.2f} [{c[1]:.2f}, {c[2]:.2f}] | {leak} | "
                 f"{'; '.join(sorted(roles.get(name, []))) or '--'} |")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=str(ROOT / "results"))
    ap.add_argument("--out", default=str(ROOT / "paper" / "tables"))
    a = ap.parse_args()
    res, out = pathlib.Path(a.results), pathlib.Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    E = json.loads((res / "evaluation.json").read_text())
    CS = json.loads((res / "counter_study.json").read_text())
    R5 = json.loads((res / "round5_analyses.json").read_text())
    (out / "headline.tex").write_text(headline(E) + "\n")
    (out / "designs.tex").write_text(designs_tex(E) + "\n")
    (out / "pumping.tex").write_text(pumping(E) + "\n")
    (out / "matched.tex").write_text(matched(E) + "\n")
    (out / "claims.tex").write_text(claims(CS) + "\n")
    ra, rb, users = attacked(R5)
    (out / "attacked_a.tex").write_text(ra + "\n")
    (out / "attacked_b.tex").write_text(rb + "\n")
    (res / "design_table.md").write_text(design_table(E))
    (res / "figure1_key.md").write_text(figure1_key(E, res / "evaluation_runs.jsonl.gz"))
    print(f"wrote {out}/*.tex and {res}/design_table.md (attacked-block users per run: {users:.1f})")


if __name__ == "__main__":
    main()
