// Response to Reviewer 2. Build: node rebuttal.js  -> rebuttal.docx
const fs = require("fs");
const { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType,
        AlignmentType, BorderStyle, ShadingType, LevelFormat } = require("docx");

const P = (text, opts = {}) => new Paragraph({ spacing: { after: 120 }, ...opts, children: runs(text) });
function runs(text) {
  // **bold** and _italic_ markup, minimal
  const out = []; const re = /(\*\*[^*]+\*\*|_[^_]+_)/g; let last = 0, m;
  while ((m = re.exec(text))) {
    if (m.index > last) out.push(new TextRun(text.slice(last, m.index)));
    const t = m[0];
    if (t.startsWith("**")) out.push(new TextRun({ text: t.slice(2, -2), bold: true }));
    else out.push(new TextRun({ text: t.slice(1, -1), italics: true }));
    last = m.index + t.length;
  }
  if (last < text.length) out.push(new TextRun(text.slice(last)));
  return out;
}
const H1 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 120 }, children: [new TextRun(t)] });
const H2 = (t) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 100 }, children: [new TextRun(t)] });
const Quote = (t) => new Paragraph({ indent: { left: 540 }, spacing: { after: 100 }, children: [new TextRun({ text: t, italics: true, color: "444444" })] });
const Bullet = (t) => new Paragraph({ numbering: { reference: "bullets", level: 0 }, spacing: { after: 60 }, children: runs(t) });

// One reviewer point: number, title, the reviewer's objection in brief, what changed (code / evaluation / manuscript), where.
function item(num, title, objection, response, where) {
  const ps = [H2(`${num}. ${title}`), Quote(objection)];
  for (const r of response) ps.push(P(r));
  if (where) ps.push(P(`Where: ${where}`, { spacing: { after: 200 } }));
  return ps;
}

const doc = new Document({
  styles: { default: { document: { run: { font: "Calibri", size: 22 } } },
            paragraphStyles: [
              { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 30, bold: true, color: "1F3864" }, paragraph: { spacing: { before: 360, after: 120 } } },
              { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true, run: { size: 24, bold: true, color: "2E5496" }, paragraph: { spacing: { before: 240, after: 80 } } }] },
  numbering: { config: [{ reference: "bullets", levels: [{ level: 0, format: LevelFormat.BULLET, text: "•", alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 540, hanging: 270 } } } }] }] },
  sections: [{ properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1250, bottom: 1250, left: 1300, right: 1300 } } },
    children: [
      new Paragraph({ children: [new TextRun({ text: "Response to the Reviewer 2 report", bold: true, size: 32 })], spacing: { after: 120 } }),
      P("**Manuscript:** From a Production OTP Flood to a Layered Defence: Measured Limits of Risk-Scored SMS Verification Against Residential Flooders and Colluding Carriers"),
      P("**Journal:** Computers & Security. **Review date:** 1 October 2026. **Reviewed artifact:** commit 818d00f. **Revised artifact:** release 2.5.0 (commits 13c12b7, 6e64bd2, 51cadcd, f457f31 on the same branch)."),

      H1("Summary"),
      P("We thank the reviewer for a report that read the code as closely as the text. The review found eleven defects in the implementation and the simulator, several of which changed results we had presented as headline findings, and it found claims in the text that the evidence did not support. We have treated the report as the specification for this revision. Every implementation and simulator defect in Section A is fixed, with a regression test where one was possible; every evaluation the reviewer asked for that we could run without production traffic has been run; the full evaluation was regenerated (6,713 runs); and the manuscript has been rewritten from the regenerated numbers with the claims narrowed to what they support. Where we could not do what was asked, we say so below and in the paper's limitations."),
      P("Three results changed materially, and we state them plainly because they matter more than the ones that did not. First, the forged-platform-header attack is no longer 'stopped by attestation': with a valid host and session, the header buys the attacker nothing under v2 (the row equals the CAPTCHA farm's) and under v1 it moves the attacker into the app bucket where a static cap holds it to 100 messages. Attestation removes the attacker's choice of bucket; it does not reduce leakage. Second, the adaptive cap's whole effect against the residential attacker depends on the controller running every minute; run hourly, as the first manuscript described, the design leaks 575 of 600 at 1.3 % first-time refusal, which is the static cap. Third, the destination-block tests as first implemented (a plain SPRT) could bank unbounded credit, as the reviewer's counterexample showed; the corrected tests bound that credit, and the bound is a measured trade-off between a verifying carrier and false verdicts on legitimate blocks, which the paper now reports rather than hides."),
      P("The paper's contribution is narrower than before and closer to what the reviewer proposed: a bounded study of destination-keyed sequential detection and its collateral damage, inside a layered system that we no longer claim 'closes' anything. The abstract, the introduction, the conclusion and twenty-one sentences the reviewer marked were rewritten to that end."),

      H1("What we could not do"),
      Bullet("**Independently sourced traffic.** We have no production logs and could not obtain any for this revision. The paper now says in the abstract, Section 3.1, Section 6.2 and the limitations that every absolute figure is conditional on an assumed behavioural calibration, and names the replay through real traffic as the experiment the paper most needs. We accept that this limits what the paper can establish, and we have removed every sentence that claimed more."),
      Bullet("**A supervised model baseline** (Huh et al. style). A model trained on synthetic features would re-learn our own generator; we say so in Section 2.2 and do not present one."),
      Bullet("**A sliding-window or change-detection alternative to the cumulative statistic.** The corrected block tests are CUSUM statistics (Page), which are a change-detection scheme; the plain cumulative SPRT is now the comparison, not the default. A windowed alternative and a time-uniform test in the sense of Howard et al. were not evaluated; both are listed as gaps."),
      Bullet("**Client puzzles.** Not evaluated; listed as a gap with the reason we doubted their relevance (the attacker is bounded by SMS price, not compute), stated as an argument and not a result."),
      Bullet("**Written permission to describe the incident.** It is being sought and the repository's ethics document records that; the manuscript now says exactly that (Section 8.3) rather than that it was obtained."),

      H1("A. Implementation and evaluation defects"),
      ...item("A1", "The transmitted message did not contain the generated code",
        "The sender received req.text; the code was generated afterwards; the simulator verified through code_for().",
        ["Correct, and we are grateful the reviewer ran it. Step 11 now generates the code before the send and renders it into the message body (a template placeholder, appended if the template has none); the audit record stores the template, never the code. The simulator verifies with the code it reads out of the delivered message text. Regression tests: test_sent_message_carries_the_code_that_verifies, test_template_without_placeholder_gets_the_code_appended."],
        "pipeline.py step11_log_and_send; evaluation/sim.py process_due_events; tests/unit/test_review_round3.py. Manuscript Section 6.1."),
      ...item("A2", "The challenge depended on the fake CAPTCHA service",
        "step7_risk checked the proof against FakeRecaptcha.scores; the Google adapter had no such attribute.",
        ["Fixed. Both adapters now expose verify_challenge(token); the pipeline calls only that. The Google adapter verifies the interactive token against the configured site key; the fake accepts tokens it issued. Tests: test_challenge_proof_goes_through_the_adapter_interface, test_google_adapter_verify_challenge_shape."],
        "providers/recaptcha.py; services.py; pipeline.py step7_risk."),
      ...item("A3", "A challenged user retried with a different number and address",
        "Simulation.run() regenerated the request on retry, so a user could leave a flagged block.",
        ["Fixed. The offered request (session, address, number, verification behaviour) is drawn once into a context and the retry re-uses it; the attacker's retry path is the same. The collateral-damage figures in Sections 7.5 and 7.6 were regenerated under this rule."],
        "evaluation/sim.py request_from / make_legit_context."),
      ...item("A4", "'Delivered' meant a channel was chosen",
        "friction.delivered incremented before receipts were processed.",
        ["Fixed. Three outcomes are now recorded and defined in the paper: dispatched (channel chosen), delivered (provider receipt), completed (code entered); a failed delivery counts as refused. The outage study now shows what it should: delivery falls to 92 % during the failed-receipt outage (Section 7.6). The abstract's '99 % delivered' is now delivery by receipt."],
        "evaluation/sim.py; evaluation/metrics.py FrictionGroup. Manuscript Section 6.4 and Table 5 caption."),
      ...item("A5", "The first-time refusal rate had the wrong denominator",
        "refused / all legitimate requests was reported as a first-time-user rate.",
        ["Fixed. Friction is now accumulated per group (first-time: no verified history; returning) from recorded identities, and the paper reports the group rates. The reviewer's arithmetic was right: the figure that was 42 % of all requests is 51 % of first-time users (returning users 0.5 %; all users 40 %, 60 % delivered). Every sentence that quoted the old figure was corrected (abstract, Sections 7.1, 7.4, 9)."],
        "evaluation/metrics.py; results/evaluation.md columns 'First-time refused %', 'Returning refused %'."),
      ...item("A6", "Table 6 swept OTP validity, not the resolution timeout",
        "otp_ttl_s changed cfg.otp_ttl; resolution stayed at 120 s.",
        ["Correct. The sweep now varies resolution_timeout_s over 60, 120, 300 and 600 s. The result is unchanged (no effect on the farm attacker) and the table says what was swept and that the earlier version did not."],
        "evaluation/runner.py SWEEP_AXES; Table 7 (formerly 6) and its caption."),
      ...item("A7", "The adaptive controller ran every minute, not hourly",
        "The paper described an hourly job on a four-week baseline; the simulator updated every minute with the known legitimate rate.",
        ["The simulator was the honest side of this mismatch and the paper was not, so we changed the paper and added the experiment the reviewer implies. The default worker runs the baseline job every minute (Section 4.5 now says so), and a cadence study (Section 7.4) runs the same design at one-minute, ten-minute and hourly cadence: 256, 565 and 575 leaked against the farm, at 47.5 %, 2.0 % and 1.3 % first-time refusal. The paper now states that the adaptive cap's effect exists only at the fast cadence and that whether such a controller is operable is a deployment question. The known legitimate rate standing in for the four-week baseline is listed as a limitation."],
        "evaluation/runner.py study_cadence; results/evaluation.md B2."),
      ...item("A8", "The default worker did not run the baseline job",
        "worker.main() called run_forever without a baseline_source.",
        ["Fixed. Step 9 records per-key volume; a BaselineJob reads the pipeline's own counters and recomputes the multiplier; the default worker runs it. Test: test_default_worker_runs_the_baseline_job."],
        "src/otp_guard/baseline.py; worker.py."),
      ...item("A9", "The spoofed-header experiment was confounded by an invalid host",
        "The generator combined the iOS header with host=attacker.local; with a valid host and session the header is simply treated as web traffic.",
        ["Correct, and this changed a headline. The attacker now forges only the header, with a valid host and session. Under v2 it is treated as web traffic and its row equals the CAPTCHA farm's (595 lifted, 243 with caps); under v1 the believed header moves it into the app bucket, whose static cap holds it to 100 with caps on. The paired ablation shows removing attestation under this attacker lowers leakage by 256 for the same reason. The paper now says that attestation removes the attacker's choice of bucket and does not reduce leakage (Sections 7.1, 7.2), and the figure caption no longer tells the old story."],
        "evaluation/sim.py (platform_spoof: header only); Section 7.1, Table 5 row 'Forged platform header'."),
      ...item("A10", "The datacenter result was attributed to the wrong tier",
        "The stated weights give 47.5 points and a challenge, not a block.",
        ["Correct. Section 4.2 now states the arithmetic (about 47, the challenge tier) and that datacenter rotation is stopped because the attacker does not solve challenges; Section 7.7 reports what happens when it does (53 to 56 leaked, with about 256 session attempts lost at the CAPTCHA gate)."],
        "Manuscript Sections 4.2, 7.1, 7.7."),
      ...item("A11", "The simulator bypassed session acquisition",
        "Sessions were issued directly by the harness, skipping the CAPTCHA/attestation gate and its costs.",
        ["Fixed. Sessions are acquired through the same CAPTCHA gate as /session; refused attempts and the tokens they consume are counted and charged to the attacker (the challenge solver loses about 256 attempts per run)."],
        "evaluation/sim.py session_through_gate; Section 6.2."),

      H1("B. Mathematical and statistical points"),
      ...item("B12", "Equation 2 is not a bound",
        "An approximation under assumed outcomes, with no error bound.",
        ["Agreed. The section is retitled 'An estimate of pumping leakage'; the text says it is an approximation under stated conditions (empty history, no credit, no solved challenges, no exemptions, no suspension) and reports its error at nineteen configurations, evaluated on the observed block count: within 7 messages up to 30 blocks and within 19 everywhere (Table 9, Figure 5). The word 'bound' no longer appears in connection with it."],
        "Section 5; Section 7.5; Table 9."),
      ...item("B13", "Five failures suffice only from empty history",
        "After 100 verified sends the statistic sits near −200 and needs 143 failures; a warm-up attacker was untested.",
        ["This was the most consequential point in the report. The plain SPRT accumulated unbounded credit, and the trust-building pumper the reviewer asked for (500 identities and numbers verifying for ten minutes, then flooding) defeats it. The tests are now CUSUM statistics with a floor. We evaluated three floors side by side: no credit (Page's CUSUM), one threshold of credit (the deployed default) and unbounded (plain SPRT). Against a carrier verifying 60 % with human-like delay they leak 158, 440 and 575; against a legitimate block converting at 65 %, no credit produces 103 to 139 false verdicts a day touching 700 to 870 users, the default 6 to 21 and 20 to 43. The paper reports the dial and the reason for the default (Sections 4.4, 7.5, 7.6). The trust-building pumper is in Section 7.7: it leaks 511 (caps lifted) and 349 (caps), and the paper says the exemptions for returning users work in its favour."],
        "feedback.py (block_test = cusum, block_credit_thresholds); Table 8; Section 7.7."),
      ...item("B14", "42 % is a zero-drift point, not an evasion guarantee",
        "No crossing probability, no guarantee either side, no strategic ordering, no joint evasion.",
        ["Agreed. Section 5 now calls it what it is: the share at which the expected increment is zero under a Bernoulli model, below which the statistic drifts up and above which the floor decides; it says it is not a guarantee in either direction and that one point (60 %) is measured under all three floors. The abstract no longer says 'evades it only by verifying 42 %'."],
        "Section 5, Eq. (3) paragraph."),
      ...item("B15", "0.2^5 is a sequence probability, not the detector's error rate",
        "Table 9 already shows a different daily probability.",
        ["Agreed. Section 7.6 now distinguishes the probability of one run of five failures from the per-day verdict probability of the continuously running, restarting, two-statistic test, and the Monte Carlo now simulates the deployed statistics including the floor. The categorical sentences in the appendix ('no legitimate population converts under 10 %', 'three independent signals') are removed."],
        "Section 7.6; Appendix A."),
      ...item("B16", "The separability result is not a theorem",
        "A finite sweep cannot show no setting separates; no indistinguishability proof.",
        ["Agreed. The claim is now stated as an empirical result for the signals this design observes, with an explicit sentence that a finite sweep cannot show no setting separates and that we have not proved indistinguishability (Section 7.3). The abstract, introduction, lessons and conclusion were rewritten to match ('no signal we tested', 'in this design'). We cite Douceur for the reason the client-side keys are cheap, as background rather than as proof."],
        "Sections 1, 7.3, 8.1, 9."),
      ...item("B17", "Inconsistent calibration protocols in the false-positive experiments",
        "The 24-hour runs recalibrated the speed test to each population.",
        ["Agreed. The 24-hour study now runs both protocols, fixed deployed calibration and recalibration to the population, side by side, and the paper reports both (Section 7.6): the fixed protocol's worst cell (30 % autofill against a 20 % calibration at 29 sends a day) produces 6.6 verdicts and recalibration removes it; the 65 % conversion cells are unchanged by recalibration because the conversion assumption is the one that is wrong."],
        "runner.py LEGIT_ONLY_CALIBRATION; results/evaluation.md H2."),
      ...item("B18", "Three seeds per 24-hour cell",
        "Rare-harm claims on 0 to 2 observed verdicts need uncertainty shown.",
        ["The cells now use five seeds; the manuscript states the seed count for every study (Section 6.2) and reports the 24-hour figures as ranges with the intervals in the repository."],
        "Section 6.2; results/evaluation.md H2."),
      ...item("B19", "Same seeds do not ensure the same offered traffic",
        "One random stream drove arrivals, identities and defence-dependent draws.",
        ["Fixed. The workload stream (arrivals, identities, numbers, entry delays, delivery delays) is separate from the stream the defence's own randomness consumes, so same-seed runs are paired. The ablation now reports paired per-seed differences with intervals (Table 6)."],
        "evaluation/sim.py rng_w / rng_p; Section 6.2; Table 6."),
      ...item("B20 and B21", "Containment is retrospective over a censored horizon; 'steady state' is not established",
        "Uncontained runs were aggregated at the horizon; the final-five-minute rate is not stationarity.",
        ["Both changed. Containment time is now reported over contained seeds only, with the contained fraction alongside, and the definition says a quiet final minute can satisfy it; the late-window rate is named 'late leak' and the paper says it is a late-window rate and not a steady state (Section 6.4)."],
        "evaluation/metrics.py; runner.py summarise; Section 6.4."),
      ...item("B22", "The simulator clock could distort the speed detector",
        "Events were processed when the next request advanced the clock; sender delay was omitted.",
        ["Fixed. Events are processed at their own timestamps, and receipt timing includes the sender's queue delay."],
        "evaluation/sim.py process_due_events."),
      ...item("B23", "The spread experiment did not measure the stated number of distinct blocks",
        "Ranges were drawn with replacement; nominal counts were multiplied.",
        ["Fixed. Ranges are drawn without replacement across the seven prefixes; the number of distinct blocks the attack actually requested is recorded per run and is what the estimate uses. Table 9 has one configuration per row with nominal and observed blocks, measurement, estimate and error; Figure 5 plots leakage against the observed block count. The '3,000 blocks' configuration reaches 509 distinct blocks in 600 requests, which the table shows."],
        "evaluation/sim.py attacker_number; Table 9; Figure 5."),

      H1("C. Threat model, comparison and system points"),
      ...item("C24", "No independently validated behavioural calibration",
        "'Calibrated' is stronger than the evidence.",
        ["Agreed. Section 6.2 now says the behavioural figures are assumptions, lists them, and says every absolute number is conditional on them; the word 'calibrated' is used only for prices."],
        "Section 6.2; Section 8.2."),
      ...item("C25", "The incident is not an auditable case study",
        "No logs, dates or totals.",
        ["Agreed. Section 3.1 opens by saying it is an operator's account with no logs, counts or bill figures, and that it motivates the design and nothing more. 'Documented case' is gone from the contributions."],
        "Section 3.1; contribution 1."),
      ...item("C26", "v1 is an insufficient principal baseline",
        "Compare against a corrected baseline, a budget-only controller, destination limits, conversion-only and speed-only detectors, an established statistical detector.",
        ["Six comparison designs now run through the same code: v1, v1-corrected (attestation-derived platform), budget-only, block-limit-only (five sends per block per day, no scoring), conversion-only and speed-only. The results changed what the paper claims: the flat per-block limit contains the sequential walk and the premium pumper at five messages each, better than the sequential tests on the walk, and the paper now says a counter is enough for a pumper that never verifies and that the tests earn their place only against carriers that verify (Sections 6.3, 7.1, 8.1). The 'established statistical detector' we did not add beyond the CUSUM/SPRT comparison; a supervised model is not meaningful on synthetic features, as discussed above."],
        "config.py BASELINE_DESIGNS; Table 5; Section 7.1."),
      ...item("C27", "The ablation masks interactions and omits user harm",
        "Leave-one-out without pairing, uncertainty or user-side effect.",
        ["The ablation now reports paired per-seed differences with intervals for both leakage and legitimate delivery (Table 6) and the text says the cells are marginal, not total, contributions. The user-side column changed the reading of two rows: removing the feedback loop under the reused-profile attacker costs 35 points of delivery as the cap tightens on everyone, and removing attestation under the forged header raises delivery by 37 points because the attacker leaves the web bucket."],
        "Table 6; Section 7.2."),
      ...item("C28", "A verifying attacker can earn the exemptions meant for genuine users",
        "A trust-building attacker is needed before claiming the exemptions preserve containment.",
        ["Added (trust_building_pumper). It leaks 511 and 349 and keeps 262 and 194 verified accounts; the paper says nothing in the design distinguishes earned trust from bought trust and that only the caps and the budget bound it (Section 7.7, lesson 3, limitations)."],
        "runner.py ADAPTIVE_ATTACKERS; Section 7.7."),
      ...item("C29", "Signed fingerprints are not proof of a trustworthy device",
        "The manuscript conflated token integrity with identity uniqueness.",
        ["Agreed. The introduction and Section 2.4 now say the signature protects the token, not the uniqueness of the fingerprint, and that nothing scarce backs a web identity (Douceur); per-identity controls tax identity reset, they do not prevent it."],
        "Sections 1, 2.4, 7.3."),
      ...item("C30", "The receipt-based defence trusts the adversary's infrastructure",
        "Receipt manipulation was deferred to limitations.",
        ["Evaluated. The receipt-faking carrier reports every delivery as failed, feeds the tests nothing, and leaks 567 (caps lifted) and 255 (caps) with no verdict ever (Section 7.7). The threat model states the billing assumption explicitly (an undelivered-reported message is assumed billed and revenue-bearing, the case that favours the attacker). Lesson 5 says the receipt comes from the adversary's side of the network."],
        "Section 3.3; Section 7.7."),
      ...item("C31", "The global budget was not a hard bound",
        "Emergency mode still sent; utilisation was checked separately from spend.",
        ["Fixed. Step 10 now reserves the hourly count and spend atomically before a send and refuses the send if either is exhausted; emergency mode operates below the ceiling, not instead of it. Test: test_hard_budget_ceiling_is_atomic_and_unconditional."],
        "pipeline.py reserve_budget; store.py try_reserve/release; Table 2 row 10."),
      ...item("C32", "Atomicity was overstated",
        "Per-number check in Step 8 and update in Step 11; feedback and verdict transitions multi-step; no concurrency tests.",
        ["Fixed and tested. The per-number window and daily slot are claimed atomically in Step 8 and released if a later step refuses; delivery and verification callbacks are idempotent. Tests: test_per_number_claim_is_atomic_under_concurrency, test_number_claim_released_when_a_later_step_refuses, test_duplicate_callbacks_are_idempotent. Section 4.1 now describes which operations are atomic and no longer says 'every rate limit is one operation'."],
        "pipeline.py; feedback.py; tests/unit/test_review_round3.py."),
      ...item("C33", "The fallback channel benefit is not demonstrated for new registrations",
        "'Non-SMS' is not a generally available alternative.",
        ["The simulation now states its assumption: 70 % of users are reachable on WhatsApp, the downgrade channel for someone with no registered device, and for the rest a downgrade is a refusal; refusals are counted accordingly. The assumption is listed in Section 6.2 and the limitations."],
        "evaluation/sim.py LegitSpec.whatsapp_fraction; Sections 6.2, 8.2."),
      ...item("C34", "The economic model does not establish profitability in deployment",
        "Retail price as termination revenue; charging after containment.",
        ["Agreed. Section 7.7 now states the accounting and its two biases in the same paragraph as the numbers, and the sentence 'the attacker loses money' is gone; one of the numbers reversed (the instant verifier earns 0.85 USD at the 50 % share under v2), and the paper reports it."],
        "Section 7.7."),
      ...item("C35 and C36", "Timing indistinguishability is not established; uniform responses are contradicted",
        "KS non-rejection is not indistinguishability; challenges and Step 0 differ.",
        ["Both changed. Section 4.1 now gives the observable contract: one body for every outcome after Step 0 except the challenge, 403 at Step 0, a minimum response time. The load test includes the challenge class (five outcome classes, 6,000 requests, a corrected host so the challenge path is exercised); the paper reports no distinguishable pair at this sample size (smallest KS p = 0.32, every pair within 2 ms by TOST) and says exactly what that does and does not establish (Section 7.7)."],
        "scripts/load_test.py; results/performance.md; Sections 4.1, 7.7."),
      ...item("C37", "No test of maliciously induced collateral damage",
        "An attacker poisoning a block shared with legitimate users is the central risk.",
        ["Added (block_poisoner). It earns verdicts on 12 and 8 blocks per run and makes 25 % and 11 % of simulated users solve a challenge, with delivery at 96 % and 69 %. The paper calls it the central risk of destination-keyed reputation and says the grading is the only mitigation we have (Section 7.6, lesson 4)."],
        "runner.py; Section 7.6."),
      ...item("C38", "Important operating conditions are missing",
        "Retries, synchronised bursts, multi-day attacks, verdict expiry, device farms, mixed blocks, carrier changes, vendor error correlations.",
        ["Not evaluated. The limitations now list them explicitly, and the broad statements about robustness and returning-user protection they would have been needed to support are removed."],
        "Section 8.2."),
      ...item("C39", "Ethics and retention statements disagree with the artifact",
        "Permission recorded as pending; 90-day first-seen record and trusted-number set omitted.",
        ["Corrected. Section 8.3 now says permission is being sought, describes the incident as an operator's recollection without identifying the operator, and lists the 90-day fingerprint first-seen record and the trusted-number set kept until cleared."],
        "Section 8.3; docs/privacy_and_ethics.md."),

      H1("Section 3 of the report: the marked sentences"),
      P("Every sentence in the reviewer's table was rewritten or removed. In summary:"),
      Bullet("'Stopped completely' (abstract, §1, §7.1, §9): replaced by 'contained', with the residue stated (2 for the single client, 65 to 71 for the walk) and the two zero-leakage attacks named."),
      Bullet("'Bounds leakage ... evades it only by verifying 42 %' (abstract): replaced by 'leaks about five messages per block plus the in-flight window, to within 19 messages of a closed-form estimate at every configuration measured, until the carrier verifies its own codes or fakes delivery receipts'."),
      Bullet("'Closes them' (§1): replaced by 'is built around them'; Table 2's last column is now 'built against', with the sentence that whether a step closes a gap is what Section 7 measures."),
      Bullet("'Works from day one without labels ... explicit bounds on the harm' (§2.2): replaced by a narrower statement of what the paper adds beside Huh et al., and the sentence that we did not reproduce their detector."),
      Bullet("'As good as the provider's list' (§2.3): replaced by a description of both Fraud Guard and the SMS Pumping Risk Score, which we now read and cite, and the statement that a risk score with graded action on the destination is established commercial practice."),
      Bullet("'What it does not contain ...' (§2.5): the absence claim is removed; Section 2 ends on the two prior findings the paper builds on instead."),
      Bullet("'They are not implementation bugs' (§3.2): replaced by 'two of them ... are design defects by any standard'."),
      Bullet("'The same response' and 'every rate limit is a single Lua script' (§4.1): replaced by the observable contract and the list of which operations are atomic."),
      Bullet("'In every one of these cases 99 % ... delivered' (§7.1): replaced by '99 % or more with the caps lifted, and 95 to 99 % with caps on'; the attribution of challenges to the corporate/roaming/cloud minority is now stated as the generator's attribution."),
      Bullet("'No setting changes this' and 'tuning cannot change it' (§7.3, §8.1): replaced by 'no signal we tested' and an explicit sentence that a finite sweep cannot show no setting separates."),
      Bullet("'The only lever' (§7.4): replaced by 'the lever this design has'."),
      Bullet("'Its cost has moved from the SMS bill' (§7.5): rewritten; the SMS bill remains and the accounts are additional."),
      Bullet("'Within a few messages' (§7.5): replaced by the measured errors, within 7 up to 30 blocks and within 19 everywhere, with the saturated points shown numerically in Table 9 rather than as '≈N'."),
      Bullet("'Spread ... paid on fewer of them' (§8.1): removed."),
      Bullet("§9: rewritten without 'every', 'without touching', or 'no setting of its parameters will'; 'real users' is 'simulated users' throughout the results."),
      Bullet("Artifact availability: now says which script draws the figures and that performance numbers depend on the machine."),
      Bullet("Appendix A: the two categorical sentences are removed and the table is labelled as design judgements, not findings."),

      H1("Section 4 of the report: numerical contradictions"),
      P("All were resolved by regenerating every number from release 2.5.0 and rewriting the text from the tables. Specifically: the single client and the walk are described as contained with their residue, not stopped; the '99 % in every case' sentence is gone; the first-time denominator is fixed (51 %, with 60 % overall delivery and 99.5 % returning delivery); the 0.2^5 figure is distinguished from the per-day verdict probability; the block-density sentence in §4.4 now cites the densities the 24-hour study uses; the 130-minute warm-up of the pumping study is stated in §6.2 and Table 8; the difference between Table 8's 99 and Table 9's 84 to 96 for the same attacker is the warm-up and is noted; the timeout row is correctly labelled; the spread table shows every discrepancy numerically; the low-and-slow and elevated-range figures are quoted from the regenerated tables (41 and 198; 7 for the instant verifier under the speed test, 20 for the human-like one under the prefix cap, stated as two different mechanisms); and the seed counts of every study are listed in §6.2."),

      H1("Section 5 of the report: related work"),
      P("We read each of the five works the reviewer named before citing it. Huh et al. is now 'confronted' to the extent we can without their data: Section 2.2 states exactly what the paper adds beside it and that a supervised model on synthetic features is not a meaningful comparison. Twilio's SMS Pumping Risk Score is described from its documentation (signals, score range, graded guidance) and the commercial baseline is no longer portrayed as list-based. Douceur's Sybil argument now grounds the identity discussion and the separability section. Howard et al. is cited for time-uniform confidence sequences, with the statement that our tests are classical and their error rates are reported empirically, and a time-uniform test is listed as the right next step. Dean and Stubblefield are cited for client puzzles as an unevaluated alternative, with our doubt stated as an argument rather than a result. Page (1954) is added for the CUSUM. Of the seven missing baselines the reviewer listed, four are now run (corrected v1, budget-only, block-limit-only, conversion-only and speed-only) and three adaptive attackers were added (trust-building, receipt-faking, poisoning); the windowed detector and the supervised model are not run and are listed as gaps."),

      H1("Section 6 of the report: figures and tables"),
      Bullet("Figure 1: 95 % bands added; the caption separates zero from the first minute from containment after a few minutes."),
      Bullet("Figure 2: labels enlarged and reworded ('without X'); paired differences, intervals and user harm are in the new Table 6; the attestation column under the forged header is explained in the text as the bucket effect."),
      Bullet("Figure 3: five seeds stated; intervals drawn; refused users added as a third line."),
      Bullet("Figure 4: the index is defined as 'refused plus challenged, a user can count under both'; the line is described as the nondominated set of sampled settings, with the note that intermediate policies were not run."),
      Bullet("Figure 5: redrawn with the observed distinct block count on the x-axis, the estimate overlaid, and bands defined in the caption."),
      Bullet("Table 2: 'closes' is now 'built against'; Gap G is mapped to Steps 5 and 6; 'constant response time' is 'a 400 ms minimum response time'."),
      Bullet("Table 3: the instant-verification contribution is included; the text says the signals are correlated and the score is a tally, not a probability."),
      Bullet("Table 5: counts and percentages are in separate columns for v2; 'real users' is 'simulated users'; first-time denominators; the caption directs to the intervals."),
      Bullet("Table 7 (sweep): the resolution-window row is correctly labelled; the caption says the attack size varies per seed."),
      Bullet("Table 8 (pumping): columns no longer run together; the contained fraction and conditional time are in one labelled cell ('9 of 10 (10.3)')."),
      Bullet("Table 9 (spread): one configuration per row with observed blocks, measurement, estimate and signed error; no '≈N'."),
      Bullet("Table 10 (Monte Carlo): header clarified; 0.00 % is defined as fewer than one trial in 20,000."),
      Bullet("Appendix A: no longer collides with the footer; categorical claims removed; 'Appendix Appendix A' fixed."),
      Bullet("Structure: §6.4 has text; tables and figures are placed near their references; 'TODO' affiliation and co-author placeholders remain for the author to complete at submission."),
      Bullet("Tone: 'we built it and tried to break it', 'the honest statement' and 'can honestly claim' are removed."),

      H1("Section 7 of the report: the single question"),
      P("The reviewer asks whether, after the fixes, we can show on independently sourced traffic that destination-block sequential testing gives a reproducible reduction in leakage at a matched completion rate, beyond a corrected limiter and a simpler destination detector, including attackers that earn trust and manipulate timing. Our answer, which the revised paper now states rather than avoids, has three parts. On the simpler detector: against a pumper that never verifies, a flat per-block limit does as well or better, and the sequential tests add value only against carriers that enter codes (Table 5, Table 8). On trust-earning and timing-manipulating attackers: the trust-building pumper and the receipt-faking carrier defeat the block tests and are bounded only by the caps and the budget; the human-like verifier is caught or not depending on a memory setting whose other side is false verdicts on legitimate blocks. On independently sourced traffic: we do not have it. The paper therefore no longer claims a security advance over contemporary practice; it claims a measured account, in simulation, of where one explicit destination-keyed detector works, where it is defeated, and what it costs the people in the blocks it judges. We believe that account is useful to the journal's readers for the same reason the reviewer's report was useful to us, and we leave the editor to judge whether it is enough."),
    ] }]
});

Packer.toBuffer(doc).then(buf => { fs.writeFileSync("rebuttal.docx", buf); console.log("wrote rebuttal.docx"); });
